# Generated by Django 3.0.7 on 2020-06-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
