# Generated by Django 3.0.7 on 2020-06-26 00:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200626_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expires_doc',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 0, 40, 19, 467641, tzinfo=utc)),
        ),
    ]
