# Generated by Django 3.0.7 on 2020-06-26 00:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20200626_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='duration',
        ),
        migrations.AlterField(
            model_name='document',
            name='expires_doc',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 0, 54, 21, 255426, tzinfo=utc)),
        ),
    ]
