# Generated by Django 3.0.7 on 2020-06-26 00:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20200626_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expires_doc',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 0, 56, 52, 338975, tzinfo=utc)),
        ),
    ]
